In [ ]:
import math

import numpy as np
import scipy
import torch
from sentence_transformers import SentenceTransformer


In [6]:
# Example documents
documents = [
    'Bugs introduced by the intern had to be squashed by the lead developer.',
    'Bugs found by the quality assurance engineer were difficult to debug.',
    'Bugs are common throughout the warm summer months, according to the entomologist.',
    'Bugs, in particular spiders, are extensively studied by arachnologists.'
]
json_docs = {'payload_version': '3', 'imei': '359404230682727', 'modem_plmn': '311480', 'gsm_lac': '0x0C00', 'gsm_cid': '0x00303803', 'gsm_rssi': '-103', 'latitude': '0.0', 'longitude': '0.0', 'filter_status': '0', 'filter_count': '0', 'filter_sum_removed_time': '10803', 'filter_time_since_last_change': '10803', 'hopper1_status': '1', 'hopper1_count': '0', 'hopper1_sum_low_time': '0', 'hopper1_time_since_last_change': '0', 'hopper2_status': '1', 'hopper2_count': '0', 'hopper2_sum_low_time': '0', 'hopper2_time_since_last_change': '0', 'temp_current': '34.2', 'temp_count_over': '19', 'temp_sec_over': '4664', 'temp_max': '53.9', 'meltdown_triggered': '0', 'max_under_time': '688', 'bowl1_status': '1', 'bowl1_count': '0', 'bowl1_sum_removed_time': '0', 'bowl1_time_since_last_change': '0', 'bowl2_status': '1', 'bowl2_count': '0', 'bowl2_sum_removed_time': '0', 'bowl2_time_since_last_change': '0', 'bunn_connection_status': '1', 'compressor_status': '0', 'compressor_count': '31', 'compressor_enabled_sum_time': '6135', 'compressor_time_since_last_change': '10', 'left_auger_on_status': '1', 'left_auger_on_count': '0', 'left_auger_on_sum_time': '335560', 'left_auger_on_time_since_last_change': '335560', 'left_auger_refill_status': '0', 'left_auger_refill_count': '0', 'left_auger_refill_sum_time': '0', 'left_auger_refill_time_since_last_change': '335564', 'right_auger_on_status': '1', 'right_auger_on_count': '0', 'right_auger_on_sum_time': '335560', 'right_auger_on_time_since_last_change': '335560', 'right_auger_refill_status': '0', 'right_auger_refill_count': '0', 'right_auger_refill_sum_time': '0', 'right_auger_refill_time_since_last_change': '335564', 'gas_temperature_min': '20.7', 'gas_temperature_max': '53.9', 'gas_temperature_mean': '35.8', 'gas_temperature_stddev': '8.21', 'left_temperature_min': '-2.3', 'left_temperature_max': '-1.7', 'left_temperature_mean': '-2.1', 'left_temperature_stddev': '0.16', 'right_temperature_min': '-2.3', 'right_temperature_max': '-1.7', 'right_temperature_mean': '-2.0', 'right_temperature_stddev': '0.15', 'left_torque_min': '17.0', 'left_torque_max': '41.0', 'left_torque_mean': '22.39', 'left_torque_stddev': '3.92', 'right_torque_min': '17.0', 'right_torque_max': '32.0', 'right_torque_mean': '21.36', 'right_torque_stddev': '2.71', 'left_hopper_status': '12', 'right_hopper_status': '16', 'left_thickness': '8', 'right_thickness': '8', 'sw_version': '2.12.5', 'event_time': '2026-02-16T21:44:36.535829+00:00'}

In [3]:
# Load a pre-trained model
model = SentenceTransformer('paraphrase-MiniLM-L6-v2')

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

/home/samuel/Desktop/ai_applications_coursera/venv/lib/python3.12/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/314 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [8]:
# Generate embeddings
import json
embeddings = model.encode(json.dumps(json_docs))
embeddings.shape
embeddings

array([-4.17534187e-02,  3.86949666e-02, -1.78760365e-01, -2.96867430e-01,
        1.18234634e-01, -2.02654153e-01,  8.64148736e-02, -1.82105795e-01,
       -3.43832254e-01,  9.28088576e-02,  1.25312582e-01, -6.30194068e-01,
        5.24864532e-02, -1.67609341e-02, -9.08578038e-02,  2.24155083e-01,
       -1.81504920e-01, -1.23565748e-01,  3.07301104e-01, -6.39870688e-02,
        1.26683086e-01, -1.83856282e-02, -3.49158794e-01,  3.16979796e-01,
        8.50089565e-02,  4.55118775e-01,  3.66661042e-01,  4.50385123e-01,
       -3.79744947e-01, -1.35424957e-02,  2.76282609e-01, -1.67617261e-01,
        2.95579225e-01,  4.85277146e-01,  1.20628886e-01,  6.97770715e-02,
       -1.45279929e-01, -2.23060157e-02,  1.06796250e-01,  9.75980759e-02,
       -1.53725386e-01, -1.59473382e-02,  1.51251659e-01, -6.71666935e-02,
        3.91841471e-01,  1.76479176e-01, -1.68680519e-01, -1.36844665e-01,
       -1.50033131e-01, -1.41971549e-02,  1.25605673e-01,  8.88664424e-02,
       -4.47800428e-01,  

In [13]:
# Load a pre-trained model
model = SentenceTransformer('paraphrase-MiniLM-L6-v2')
embeddings = model.encode(documents)
embeddings.shape
embeddings

/home/samuel/Desktop/ai_applications_coursera/venv/lib/python3.12/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


array([[-0.22804378, -0.2464769 , -0.00319263, ...,  0.45528135,
         0.6341971 ,  0.537505  ],
       [-0.35791588, -0.32083976,  0.15963262, ..., -0.07050662,
         0.9275022 ,  0.34377328],
       [ 0.20302922, -0.2689859 ,  0.16285127, ..., -0.19651009,
        -0.03379851,  0.5956153 ],
       [-0.04264295, -0.45721602, -0.09526497, ..., -0.58030707,
         0.17248404,  0.09127875]], dtype=float32)

In [14]:
def euclidean_distance_fn(vector1, vector2):
    squared_sum = sum((x - y) ** 2 for x, y in zip(vector1, vector2))
    return math.sqrt(squared_sum)

In [15]:
euclidean_distance_fn(embeddings[0], embeddings[1])

5.961788408720014

In [16]:
l2_dist_manual = np.zeros([4,4])
for i in range(embeddings.shape[0]):
    for j in range(embeddings.shape[0]):
        l2_dist_manual[i,j] = euclidean_distance_fn(embeddings[i], embeddings[j])

l2_dist_manual

array([[0.        , 5.96178841, 7.33940009, 7.15578196],
       [5.96178841, 0.        , 7.76861545, 7.39359023],
       [7.33940009, 7.76861545, 0.        , 5.91992706],
       [7.15578196, 7.39359023, 5.91992706, 0.        ]])

In [17]:
l2_dist_manual[0,1]

5.961788408720014

In [18]:
l2_dist_manual[1,0]

5.961788408720014

In [20]:
l2_dist_manual_improved = np.zeros([4,4])
for i in range(embeddings.shape[0]):
    for j in range(embeddings.shape[0]):
        if j > i: # Calculate the upper triangle only
            l2_dist_manual_improved[i,j] = euclidean_distance_fn(embeddings[i], embeddings[j])
        elif i > j: # Copy the uper triangle to the lower triangle
            l2_dist_manual_improved[i,j] = l2_dist_manual[j,i]


l2_dist_manual_improved

array([[0.        , 5.96178841, 7.33940009, 7.15578196],
       [5.96178841, 0.        , 7.76861545, 7.39359023],
       [7.33940009, 7.76861545, 0.        , 5.91992706],
       [7.15578196, 7.39359023, 5.91992706, 0.        ]])

In [21]:
l2_dist_scipy = scipy.spatial.distance.cdist(embeddings, embeddings, 'euclidean')
l2_dist_scipy

array([[0.        , 5.9617884 , 7.3394001 , 7.15578196],
       [5.9617884 , 0.        , 7.76861544, 7.39359024],
       [7.3394001 , 7.76861544, 0.        , 5.91992703],
       [7.15578196, 7.39359024, 5.91992703, 0.        ]])

In [22]:
np.allclose(l2_dist_manual, l2_dist_scipy)

True

In [23]:
def dot_product_fn(vector1, vector2):
    return sum(x * y for x, y in zip(vector1, vector2))

In [24]:
dot_product_fn(embeddings[0], embeddings[1])

18.535410536154814

In [25]:
dot_product_manual = np.empty([4,4])
for i in range(embeddings.shape[0]):
    for j in range(embeddings.shape[0]):
        dot_product_manual[i,j] = dot_product_fn(embeddings[i], embeddings[j])

dot_product_manual

array([[33.74441405, 18.53541054,  8.56981549,  7.83093121],
       [18.53541054, 38.86932801,  7.88997657,  8.66340766],
       [ 8.56981549,  7.88997657, 37.26201077, 17.66956918],
       [ 7.83093121,  8.66340766, 17.66956918, 33.12266372]])

In [26]:
# Matrix multiplication operator
dot_product_operator = embeddings @ embeddings.T
dot_product_operator

array([[33.74442  , 18.535414 ,  8.569818 ,  7.8309317],
       [18.535414 , 38.86932  ,  7.8899765,  8.663409 ],
       [ 8.569818 ,  7.8899765, 37.261997 , 17.66957  ],
       [ 7.8309317,  8.663409 , 17.66957  , 33.122665 ]], dtype=float32)

In [27]:
np.allclose(dot_product_manual, dot_product_operator, atol=1e-05)

True

In [28]:
# Equivalent to `np.matmul()` if both arrays are 2-D:
np.matmul(embeddings,embeddings.T)

array([[33.74442  , 18.535414 ,  8.569818 ,  7.8309317],
       [18.535414 , 38.86932  ,  7.8899765,  8.663409 ],
       [ 8.569818 ,  7.8899765, 37.261997 , 17.66957  ],
       [ 7.8309317,  8.663409 , 17.66957  , 33.122665 ]], dtype=float32)

In [29]:
# `np.dot` returns an identical result, but `np.matmul` is recommended if both arrays are 2-D:
np.dot(embeddings,embeddings.T)

array([[33.74442  , 18.535414 ,  8.569818 ,  7.8309317],
       [18.535414 , 38.86932  ,  7.8899765,  8.663409 ],
       [ 8.569818 ,  7.8899765, 37.261997 , 17.66957  ],
       [ 7.8309317,  8.663409 , 17.66957  , 33.122665 ]], dtype=float32)

In [30]:
dot_product_distance = -dot_product_manual
dot_product_distance

array([[-33.74441405, -18.53541054,  -8.56981549,  -7.83093121],
       [-18.53541054, -38.86932801,  -7.88997657,  -8.66340766],
       [ -8.56981549,  -7.88997657, -37.26201077, -17.66956918],
       [ -7.83093121,  -8.66340766, -17.66956918, -33.12266372]])

In [31]:
# L2 norms
l2_norms = np.sqrt(np.sum(embeddings**2, axis=1))
l2_norms

array([5.8089943, 6.234527 , 6.104262 , 5.7552295], dtype=float32)

In [32]:
# L2 norms reshaped
l2_norms_reshaped = l2_norms.reshape(-1,1)
l2_norms_reshaped

array([[5.8089943],
       [6.234527 ],
       [6.104262 ],
       [5.7552295]], dtype=float32)

In [33]:
normalized_embeddings_manual = embeddings/l2_norms_reshaped
normalized_embeddings_manual

array([[-0.03925702, -0.04243022, -0.0005496 , ...,  0.07837524,
         0.10917503,  0.09252978],
       [-0.05740866, -0.05146176,  0.02560461, ..., -0.01130906,
         0.14876865,  0.05514023],
       [ 0.03326024, -0.04406526,  0.02667829, ..., -0.03219228,
        -0.00553687,  0.09757368],
       [-0.00740943, -0.07944358, -0.01655277, ..., -0.10083126,
         0.02996997,  0.01586014]], dtype=float32)

In [34]:
np.sqrt(np.sum(normalized_embeddings_manual**2, axis=1))

array([1.        , 1.        , 1.        , 0.99999994], dtype=float32)

In [35]:
normalized_embeddings_torch = torch.nn.functional.normalize(
    torch.from_numpy(embeddings)
).numpy()
normalized_embeddings_torch

array([[-0.03925702, -0.04243022, -0.0005496 , ...,  0.07837524,
         0.10917503,  0.09252978],
       [-0.05740867, -0.05146177,  0.02560461, ..., -0.01130906,
         0.14876866,  0.05514024],
       [ 0.03326024, -0.04406527,  0.02667829, ..., -0.03219228,
        -0.00553687,  0.09757369],
       [-0.00740943, -0.07944358, -0.01655277, ..., -0.10083126,
         0.02996997,  0.01586014]], dtype=float32)

In [36]:
np.allclose(normalized_embeddings_manual, normalized_embeddings_torch)

True

In [37]:
dot_product_fn(normalized_embeddings_manual[0], normalized_embeddings_manual[1])

0.5117970041372928

In [38]:
cosine_similarity_manual = np.empty([4,4])
for i in range(normalized_embeddings_manual.shape[0]):
    for j in range(normalized_embeddings_manual.shape[0]):
        cosine_similarity_manual[i,j] = dot_product_fn(
            normalized_embeddings_manual[i], 
            normalized_embeddings_manual[j]
        )

cosine_similarity_manual

array([[0.99999997, 0.511797  , 0.24167814, 0.23423393],
       [0.511797  , 0.99999999, 0.20731897, 0.24144743],
       [0.24167814, 0.20731897, 0.99999994, 0.5029562 ],
       [0.23423393, 0.24144743, 0.5029562 , 0.99999992]])

In [39]:
cosine_similarity_operator = normalized_embeddings_manual @ normalized_embeddings_manual.T
cosine_similarity_operator

array([[1.0000002 , 0.51179695, 0.2416781 , 0.2342339 ],
       [0.51179695, 1.        , 0.20731896, 0.24144745],
       [0.2416781 , 0.20731896, 1.        , 0.50295615],
       [0.2342339 , 0.24144745, 0.50295615, 0.9999999 ]], dtype=float32)

In [40]:
np.allclose(cosine_similarity_manual, cosine_similarity_operator)

True

In [41]:
1 - cosine_similarity_manual

array([[2.84749717e-08, 4.88202996e-01, 7.58321865e-01, 7.65766066e-01],
       [4.88202996e-01, 1.33718387e-08, 7.92681032e-01, 7.58552569e-01],
       [7.58321865e-01, 7.92681032e-01, 6.28486685e-08, 4.97043804e-01],
       [7.65766066e-01, 7.58552569e-01, 4.97043804e-01, 7.64802747e-08]])